/*
Apodeixis notifications-router-svc

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the RegisterServiceRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RegisterServiceRequest{}

// RegisterServiceRequest struct for RegisterServiceRequest
type RegisterServiceRequest struct {
	Data NotificatorService `json:"data"`
}

type _RegisterServiceRequest RegisterServiceRequest

// NewRegisterServiceRequest instantiates a new RegisterServiceRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegisterServiceRequest(data NotificatorService) *RegisterServiceRequest {
	this := RegisterServiceRequest{}
	this.Data = data
	return &this
}

// NewRegisterServiceRequestWithDefaults instantiates a new RegisterServiceRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegisterServiceRequestWithDefaults() *RegisterServiceRequest {
	this := RegisterServiceRequest{}
	return &this
}

// GetData returns the Data field value
func (o *RegisterServiceRequest) GetData() NotificatorService {
	if o == nil {
		var ret NotificatorService
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *RegisterServiceRequest) GetDataOk() (*NotificatorService, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *RegisterServiceRequest) SetData(v NotificatorService) {
	o.Data = v
}

func (o RegisterServiceRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RegisterServiceRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *RegisterServiceRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRegisterServiceRequest := _RegisterServiceRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRegisterServiceRequest)

	if err != nil {
		return err
	}

	*o = RegisterServiceRequest(varRegisterServiceRequest)

	return err
}

type NullableRegisterServiceRequest struct {
	value *RegisterServiceRequest
	isSet bool
}

func (v NullableRegisterServiceRequest) Get() *RegisterServiceRequest {
	return v.value
}

func (v *NullableRegisterServiceRequest) Set(val *RegisterServiceRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRegisterServiceRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRegisterServiceRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegisterServiceRequest(val *RegisterServiceRequest) *NullableRegisterServiceRequest {
	return &NullableRegisterServiceRequest{value: val, isSet: true}
}

func (v NullableRegisterServiceRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegisterServiceRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
