/*
Apodeixis notifications-router-svc

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CreateNotificationAllOfRelationshipsDestinations type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateNotificationAllOfRelationshipsDestinations{}

// CreateNotificationAllOfRelationshipsDestinations struct for CreateNotificationAllOfRelationshipsDestinations
type CreateNotificationAllOfRelationshipsDestinations struct {
	Data []DestinationKey `json:"data"`
}

type _CreateNotificationAllOfRelationshipsDestinations CreateNotificationAllOfRelationshipsDestinations

// NewCreateNotificationAllOfRelationshipsDestinations instantiates a new CreateNotificationAllOfRelationshipsDestinations object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateNotificationAllOfRelationshipsDestinations(data []DestinationKey) *CreateNotificationAllOfRelationshipsDestinations {
	this := CreateNotificationAllOfRelationshipsDestinations{}
	this.Data = data
	return &this
}

// NewCreateNotificationAllOfRelationshipsDestinationsWithDefaults instantiates a new CreateNotificationAllOfRelationshipsDestinations object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateNotificationAllOfRelationshipsDestinationsWithDefaults() *CreateNotificationAllOfRelationshipsDestinations {
	this := CreateNotificationAllOfRelationshipsDestinations{}
	return &this
}

// GetData returns the Data field value
func (o *CreateNotificationAllOfRelationshipsDestinations) GetData() []DestinationKey {
	if o == nil {
		var ret []DestinationKey
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *CreateNotificationAllOfRelationshipsDestinations) GetDataOk() ([]DestinationKey, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *CreateNotificationAllOfRelationshipsDestinations) SetData(v []DestinationKey) {
	o.Data = v
}

func (o CreateNotificationAllOfRelationshipsDestinations) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateNotificationAllOfRelationshipsDestinations) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *CreateNotificationAllOfRelationshipsDestinations) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateNotificationAllOfRelationshipsDestinations := _CreateNotificationAllOfRelationshipsDestinations{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateNotificationAllOfRelationshipsDestinations)

	if err != nil {
		return err
	}

	*o = CreateNotificationAllOfRelationshipsDestinations(varCreateNotificationAllOfRelationshipsDestinations)

	return err
}

type NullableCreateNotificationAllOfRelationshipsDestinations struct {
	value *CreateNotificationAllOfRelationshipsDestinations
	isSet bool
}

func (v NullableCreateNotificationAllOfRelationshipsDestinations) Get() *CreateNotificationAllOfRelationshipsDestinations {
	return v.value
}

func (v *NullableCreateNotificationAllOfRelationshipsDestinations) Set(val *CreateNotificationAllOfRelationshipsDestinations) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateNotificationAllOfRelationshipsDestinations) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateNotificationAllOfRelationshipsDestinations) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateNotificationAllOfRelationshipsDestinations(val *CreateNotificationAllOfRelationshipsDestinations) *NullableCreateNotificationAllOfRelationshipsDestinations {
	return &NullableCreateNotificationAllOfRelationshipsDestinations{value: val, isSet: true}
}

func (v NullableCreateNotificationAllOfRelationshipsDestinations) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateNotificationAllOfRelationshipsDestinations) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
