/*
Apodeixis notifications-router-svc

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the DeliveryKey type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeliveryKey{}

// DeliveryKey struct for DeliveryKey
type DeliveryKey struct {
	Id   string `json:"id"`
	Type string `json:"type"`
}

type _DeliveryKey DeliveryKey

// NewDeliveryKey instantiates a new DeliveryKey object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeliveryKey(id string, type_ string) *DeliveryKey {
	this := DeliveryKey{}
	this.Id = id
	this.Type = type_
	return &this
}

// NewDeliveryKeyWithDefaults instantiates a new DeliveryKey object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeliveryKeyWithDefaults() *DeliveryKey {
	this := DeliveryKey{}
	return &this
}

// GetId returns the Id field value
func (o *DeliveryKey) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *DeliveryKey) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *DeliveryKey) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *DeliveryKey) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *DeliveryKey) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *DeliveryKey) SetType(v string) {
	o.Type = v
}

func (o DeliveryKey) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeliveryKey) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *DeliveryKey) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeliveryKey := _DeliveryKey{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeliveryKey)

	if err != nil {
		return err
	}

	*o = DeliveryKey(varDeliveryKey)

	return err
}

type NullableDeliveryKey struct {
	value *DeliveryKey
	isSet bool
}

func (v NullableDeliveryKey) Get() *DeliveryKey {
	return v.value
}

func (v *NullableDeliveryKey) Set(val *DeliveryKey) {
	v.value = val
	v.isSet = true
}

func (v NullableDeliveryKey) IsSet() bool {
	return v.isSet
}

func (v *NullableDeliveryKey) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeliveryKey(val *DeliveryKey) *NullableDeliveryKey {
	return &NullableDeliveryKey{value: val, isSet: true}
}

func (v NullableDeliveryKey) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeliveryKey) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
