/*
Apodeixis notifications-router-svc

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CreateNotificationKey type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateNotificationKey{}

// CreateNotificationKey struct for CreateNotificationKey
type CreateNotificationKey struct {
	Type string `json:"type"`
}

type _CreateNotificationKey CreateNotificationKey

// NewCreateNotificationKey instantiates a new CreateNotificationKey object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateNotificationKey(type_ string) *CreateNotificationKey {
	this := CreateNotificationKey{}
	this.Type = type_
	return &this
}

// NewCreateNotificationKeyWithDefaults instantiates a new CreateNotificationKey object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateNotificationKeyWithDefaults() *CreateNotificationKey {
	this := CreateNotificationKey{}
	return &this
}

// GetType returns the Type field value
func (o *CreateNotificationKey) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CreateNotificationKey) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CreateNotificationKey) SetType(v string) {
	o.Type = v
}

func (o CreateNotificationKey) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateNotificationKey) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *CreateNotificationKey) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateNotificationKey := _CreateNotificationKey{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateNotificationKey)

	if err != nil {
		return err
	}

	*o = CreateNotificationKey(varCreateNotificationKey)

	return err
}

type NullableCreateNotificationKey struct {
	value *CreateNotificationKey
	isSet bool
}

func (v NullableCreateNotificationKey) Get() *CreateNotificationKey {
	return v.value
}

func (v *NullableCreateNotificationKey) Set(val *CreateNotificationKey) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateNotificationKey) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateNotificationKey) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateNotificationKey(val *CreateNotificationKey) *NullableCreateNotificationKey {
	return &NullableCreateNotificationKey{value: val, isSet: true}
}

func (v NullableCreateNotificationKey) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateNotificationKey) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
