/*
Apodeixis notifications-router-svc

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the Delivery type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Delivery{}

// Delivery struct for Delivery
type Delivery struct {
	Id         string                  `json:"id"`
	Type       string                  `json:"type"`
	Attributes DeliveryAllOfAttributes `json:"attributes"`
}

type _Delivery Delivery

// NewDelivery instantiates a new Delivery object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDelivery(id string, type_ string, attributes DeliveryAllOfAttributes) *Delivery {
	this := Delivery{}
	this.Id = id
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewDeliveryWithDefaults instantiates a new Delivery object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeliveryWithDefaults() *Delivery {
	this := Delivery{}
	return &this
}

// GetId returns the Id field value
func (o *Delivery) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Delivery) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Delivery) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *Delivery) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *Delivery) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *Delivery) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *Delivery) GetAttributes() DeliveryAllOfAttributes {
	if o == nil {
		var ret DeliveryAllOfAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *Delivery) GetAttributesOk() (*DeliveryAllOfAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *Delivery) SetAttributes(v DeliveryAllOfAttributes) {
	o.Attributes = v
}

func (o Delivery) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Delivery) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *Delivery) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDelivery := _Delivery{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDelivery)

	if err != nil {
		return err
	}

	*o = Delivery(varDelivery)

	return err
}

type NullableDelivery struct {
	value *Delivery
	isSet bool
}

func (v NullableDelivery) Get() *Delivery {
	return v.value
}

func (v *NullableDelivery) Set(val *Delivery) {
	v.value = val
	v.isSet = true
}

func (v NullableDelivery) IsSet() bool {
	return v.isSet
}

func (v *NullableDelivery) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDelivery(val *Delivery) *NullableDelivery {
	return &NullableDelivery{value: val, isSet: true}
}

func (v NullableDelivery) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDelivery) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
