/*
Apodeixis notifications-router-svc

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CreateNotification type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateNotification{}

// CreateNotification struct for CreateNotification
type CreateNotification struct {
	Type          string                               `json:"type"`
	Attributes    CreateNotificationAllOfAttributes    `json:"attributes"`
	Relationships CreateNotificationAllOfRelationships `json:"relationships"`
}

type _CreateNotification CreateNotification

// NewCreateNotification instantiates a new CreateNotification object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateNotification(type_ string, attributes CreateNotificationAllOfAttributes, relationships CreateNotificationAllOfRelationships) *CreateNotification {
	this := CreateNotification{}
	this.Type = type_
	this.Attributes = attributes
	this.Relationships = relationships
	return &this
}

// NewCreateNotificationWithDefaults instantiates a new CreateNotification object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateNotificationWithDefaults() *CreateNotification {
	this := CreateNotification{}
	return &this
}

// GetType returns the Type field value
func (o *CreateNotification) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CreateNotification) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CreateNotification) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *CreateNotification) GetAttributes() CreateNotificationAllOfAttributes {
	if o == nil {
		var ret CreateNotificationAllOfAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *CreateNotification) GetAttributesOk() (*CreateNotificationAllOfAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *CreateNotification) SetAttributes(v CreateNotificationAllOfAttributes) {
	o.Attributes = v
}

// GetRelationships returns the Relationships field value
func (o *CreateNotification) GetRelationships() CreateNotificationAllOfRelationships {
	if o == nil {
		var ret CreateNotificationAllOfRelationships
		return ret
	}

	return o.Relationships
}

// GetRelationshipsOk returns a tuple with the Relationships field value
// and a boolean to check if the value has been set.
func (o *CreateNotification) GetRelationshipsOk() (*CreateNotificationAllOfRelationships, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Relationships, true
}

// SetRelationships sets field value
func (o *CreateNotification) SetRelationships(v CreateNotificationAllOfRelationships) {
	o.Relationships = v
}

func (o CreateNotification) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateNotification) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	toSerialize["relationships"] = o.Relationships
	return toSerialize, nil
}

func (o *CreateNotification) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
		"relationships",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateNotification := _CreateNotification{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateNotification)

	if err != nil {
		return err
	}

	*o = CreateNotification(varCreateNotification)

	return err
}

type NullableCreateNotification struct {
	value *CreateNotification
	isSet bool
}

func (v NullableCreateNotification) Get() *CreateNotification {
	return v.value
}

func (v *NullableCreateNotification) Set(val *CreateNotification) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateNotification) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateNotification) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateNotification(val *CreateNotification) *NullableCreateNotification {
	return &NullableCreateNotification{value: val, isSet: true}
}

func (v NullableCreateNotification) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateNotification) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
