/*
Apodeixis notifications-router-svc

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the DestinationKey type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DestinationKey{}

// DestinationKey struct for DestinationKey
type DestinationKey struct {
	Id   string `json:"id"`
	Type string `json:"type"`
}

type _DestinationKey DestinationKey

// NewDestinationKey instantiates a new DestinationKey object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDestinationKey(id string, type_ string) *DestinationKey {
	this := DestinationKey{}
	this.Id = id
	this.Type = type_
	return &this
}

// NewDestinationKeyWithDefaults instantiates a new DestinationKey object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDestinationKeyWithDefaults() *DestinationKey {
	this := DestinationKey{}
	return &this
}

// GetId returns the Id field value
func (o *DestinationKey) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *DestinationKey) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *DestinationKey) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *DestinationKey) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *DestinationKey) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *DestinationKey) SetType(v string) {
	o.Type = v
}

func (o DestinationKey) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DestinationKey) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *DestinationKey) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDestinationKey := _DestinationKey{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDestinationKey)

	if err != nil {
		return err
	}

	*o = DestinationKey(varDestinationKey)

	return err
}

type NullableDestinationKey struct {
	value *DestinationKey
	isSet bool
}

func (v NullableDestinationKey) Get() *DestinationKey {
	return v.value
}

func (v *NullableDestinationKey) Set(val *DestinationKey) {
	v.value = val
	v.isSet = true
}

func (v NullableDestinationKey) IsSet() bool {
	return v.isSet
}

func (v *NullableDestinationKey) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDestinationKey(val *DestinationKey) *NullableDestinationKey {
	return &NullableDestinationKey{value: val, isSet: true}
}

func (v NullableDestinationKey) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDestinationKey) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
