/*
Apodeixis notifications-router-svc

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the NotificatorService type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NotificatorService{}

// NotificatorService struct for NotificatorService
type NotificatorService struct {
	Type       string                            `json:"type"`
	Attributes NotificatorServiceAllOfAttributes `json:"attributes"`
}

type _NotificatorService NotificatorService

// NewNotificatorService instantiates a new NotificatorService object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNotificatorService(type_ string, attributes NotificatorServiceAllOfAttributes) *NotificatorService {
	this := NotificatorService{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewNotificatorServiceWithDefaults instantiates a new NotificatorService object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNotificatorServiceWithDefaults() *NotificatorService {
	this := NotificatorService{}
	return &this
}

// GetType returns the Type field value
func (o *NotificatorService) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *NotificatorService) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *NotificatorService) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *NotificatorService) GetAttributes() NotificatorServiceAllOfAttributes {
	if o == nil {
		var ret NotificatorServiceAllOfAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *NotificatorService) GetAttributesOk() (*NotificatorServiceAllOfAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *NotificatorService) SetAttributes(v NotificatorServiceAllOfAttributes) {
	o.Attributes = v
}

func (o NotificatorService) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NotificatorService) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *NotificatorService) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNotificatorService := _NotificatorService{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNotificatorService)

	if err != nil {
		return err
	}

	*o = NotificatorService(varNotificatorService)

	return err
}

type NullableNotificatorService struct {
	value *NotificatorService
	isSet bool
}

func (v NullableNotificatorService) Get() *NotificatorService {
	return v.value
}

func (v *NullableNotificatorService) Set(val *NotificatorService) {
	v.value = val
	v.isSet = true
}

func (v NullableNotificatorService) IsSet() bool {
	return v.isSet
}

func (v *NullableNotificatorService) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNotificatorService(val *NotificatorService) *NullableNotificatorService {
	return &NullableNotificatorService{value: val, isSet: true}
}

func (v NullableNotificatorService) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNotificatorService) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
