on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'

jobs:
  test-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.19.x
      - run: go test ./...